import Message from './common/Message.js';
import Error from './common/Error.js';
import Heartbeat from './common/Heartbeat.js';
import Ping from './common/Ping.js';
import Pong from './common/Pong.js';
import PairLong from './common/PairLong.js';
import PairString from './common/PairString.js';
import PairLS from './common/PairLS.js';
import TripleLong from './common/TripleLong.js';
import TripleString from './common/TripleString.js';
import TripleLSS from './common/TripleLSS.js';
import ChatMessage from './common/ChatMessage.js';
import TimeKeyHeaderVO from './common/time/TimeKeyHeaderVO.js';
import TimeKeyRowVO from './common/time/TimeKeyRowVO.js';
import TimeKeyVO from './common/time/TimeKeyVO.js';
import TimeLinkAlbumVO from './common/time/TimeLinkAlbumVO.js';
import VideoLinkVO from './common/time/VideoLinkVO.js';
import WebsocketSignInRequest from './user/WebsocketSignInRequest.js';
import WebsocketSignInResponse from './user/WebsocketSignInResponse.js';
import WebsocketSignOutRequest from './user/WebsocketSignOutRequest.js';
import WebsocketSignOutResponse from './user/WebsocketSignOutResponse.js';
import CreateGroupRequest from './user/group/CreateGroupRequest.js';
import CreateGroupResponse from './user/group/CreateGroupResponse.js';
import RefreshChannelTimeRequest from './user/group/RefreshChannelTimeRequest.js';
import RefreshChannelTimeResponse from './user/group/RefreshChannelTimeResponse.js';
import MuteGroupRequest from './user/group/MuteGroupRequest.js';
import MuteGroupResponse from './user/group/MuteGroupResponse.js';
import MuteChannelRequest from './user/group/MuteChannelRequest.js';
import MuteChannelResponse from './user/group/MuteChannelResponse.js';
import UserCache from './cache/model/UserCache.js';
import GetUserCacheRequest from './cache/GetUserCacheRequest.js';
import GetUserCacheResponse from './cache/GetUserCacheResponse.js';
import SearchUserRequest from './cache/SearchUserRequest.js';
import SearchUserResponse from './cache/SearchUserResponse.js';
import ApplyFriendVO from './friend/model/ApplyFriendVO.js';
import FriendInfoVO from './friend/model/FriendInfoVO.js';
import ApplyFriendRequest from './friend/operation/ApplyFriendRequest.js';
import RejectFriendRequest from './friend/operation/RejectFriendRequest.js';
import RejectFriendResponse from './friend/operation/RejectFriendResponse.js';
import AcceptFriendRequest from './friend/operation/AcceptFriendRequest.js';
import DeleteFriendRequest from './friend/operation/DeleteFriendRequest.js';
import DeleteFriendResponse from './friend/operation/DeleteFriendResponse.js';
import BlacklistRequest from './friend/operation/BlacklistRequest.js';
import BlacklistResponse from './friend/operation/BlacklistResponse.js';
import BlacklistCancelRequest from './friend/operation/BlacklistCancelRequest.js';
import BlacklistCancelResponse from './friend/operation/BlacklistCancelResponse.js';
import MarkFriendRequest from './friend/operation/MarkFriendRequest.js';
import MarkFriendResponse from './friend/operation/MarkFriendResponse.js';
import FriendChatRequest from './friend/chat/FriendChatRequest.js';
import ReadFriendMessageRequest from './friend/chat/ReadFriendMessageRequest.js';
import ReadFriendMessageResponse from './friend/chat/ReadFriendMessageResponse.js';
import FriendHistoryMessageRequest from './friend/chat/FriendHistoryMessageRequest.js';
import FriendHistoryMessageResponse from './friend/chat/FriendHistoryMessageResponse.js';
import DeleteFriendMessageRequest from './friend/chat/DeleteFriendMessageRequest.js';
import EditFriendMessageRequest from './friend/chat/EditFriendMessageRequest.js';
import FriendMessageNotice from './friend/FriendMessageNotice.js';
import NewApplyFriendNotice from './friend/NewApplyFriendNotice.js';
import NewFriendNotice from './friend/NewFriendNotice.js';
import DeleteFriendMessageNotice from './friend/DeleteFriendMessageNotice.js';
import EditFriendMessageNotice from './friend/EditFriendMessageNotice.js';
import GroupVO from './group/model/GroupVO.js';
import GroupAuthVO from './group/model/GroupAuthVO.js';
import ChannelVO from './group/model/ChannelVO.js';
import ChannelBoxVO from './group/model/ChannelBoxVO.js';
import ChannelAuthVO from './group/model/ChannelAuthVO.js';
import GroupMemberSimpleVO from './group/model/GroupMemberSimpleVO.js';
import GroupTimeVO from './group/model/GroupTimeVO.js';
import ChannelTimeVO from './group/model/ChannelTimeVO.js';
import GroupChatRequest from './group/chat/GroupChatRequest.js';
import GroupHistoryMessageRequest from './group/chat/GroupHistoryMessageRequest.js';
import GroupHistoryMessageResponse from './group/chat/GroupHistoryMessageResponse.js';
import DeleteGroupMessageRequest from './group/chat/DeleteGroupMessageRequest.js';
import EditGroupMessageRequest from './group/chat/EditGroupMessageRequest.js';
import PinGroupMessageRequest from './group/chat/PinGroupMessageRequest.js';
import DeleteGroupPinMessageRequest from './group/chat/DeleteGroupPinMessageRequest.js';
import DeleteGroupPinMessageResponse from './group/chat/DeleteGroupPinMessageResponse.js';
import GroupHistoryPinMessageRequest from './group/chat/GroupHistoryPinMessageRequest.js';
import GroupHistoryPinMessageResponse from './group/chat/GroupHistoryPinMessageResponse.js';
import SaveGroupAvatarRequest from './group/setting/SaveGroupAvatarRequest.js';
import SaveGroupAvatarResponse from './group/setting/SaveGroupAvatarResponse.js';
import SaveGroupBackgroundRequest from './group/setting/SaveGroupBackgroundRequest.js';
import SaveGroupBackgroundResponse from './group/setting/SaveGroupBackgroundResponse.js';
import SaveGroupSettingRequest from './group/setting/SaveGroupSettingRequest.js';
import SaveGroupSettingResponse from './group/setting/SaveGroupSettingResponse.js';
import RefreshGroupNameRequest from './group/setting/RefreshGroupNameRequest.js';
import CreateChannelBoxRequest from './group/channel/CreateChannelBoxRequest.js';
import CreateChannelBoxResponse from './group/channel/CreateChannelBoxResponse.js';
import CreateChannelRequest from './group/channel/CreateChannelRequest.js';
import CreateChannelResponse from './group/channel/CreateChannelResponse.js';
import DeleteChannelBoxRequest from './group/channel/DeleteChannelBoxRequest.js';
import DeleteChannelBoxResponse from './group/channel/DeleteChannelBoxResponse.js';
import DeleteChannelRequest from './group/channel/DeleteChannelRequest.js';
import DeleteChannelResponse from './group/channel/DeleteChannelResponse.js';
import SaveChannelRequest from './group/channel/SaveChannelRequest.js';
import SaveChannelResponse from './group/channel/SaveChannelResponse.js';
import SaveChannelBoxRequest from './group/channel/SaveChannelBoxRequest.js';
import SaveChannelBoxResponse from './group/channel/SaveChannelBoxResponse.js';
import InviteCodeVO from './group/member/model/InviteCodeVO.js';
import GroupMemberVO from './group/member/model/GroupMemberVO.js';
import CreateInviteGroupCodeRequest from './group/member/CreateInviteGroupCodeRequest.js';
import CreateInviteGroupCodeResponse from './group/member/CreateInviteGroupCodeResponse.js';
import JoinGroupRequest from './group/member/JoinGroupRequest.js';
import JoinGroupResponse from './group/member/JoinGroupResponse.js';
import JoinGroupByUserIdRequest from './group/member/JoinGroupByUserIdRequest.js';
import DeleteInviteGroupCodeRequest from './group/member/DeleteInviteGroupCodeRequest.js';
import DeleteInviteGroupCodeResponse from './group/member/DeleteInviteGroupCodeResponse.js';
import LeaveGroupRequest from './group/member/LeaveGroupRequest.js';
import LeaveGroupResponse from './group/member/LeaveGroupResponse.js';
import AllInviteGroupCodeRequest from './group/member/AllInviteGroupCodeRequest.js';
import AllInviteGroupCodeResponse from './group/member/AllInviteGroupCodeResponse.js';
import GroupMemberListRequest from './group/member/GroupMemberListRequest.js';
import GroupMemberListResponse from './group/member/GroupMemberListResponse.js';
import GroupMemberInfoRequest from './group/member/GroupMemberInfoRequest.js';
import GroupMemberInfoResponse from './group/member/GroupMemberInfoResponse.js';
import KickMemberRequest from './group/member/KickMemberRequest.js';
import KickMemberResponse from './group/member/KickMemberResponse.js';
import CreateGroupAuthRequest from './group/auth/CreateGroupAuthRequest.js';
import DeleteGroupAuthRequest from './group/auth/DeleteGroupAuthRequest.js';
import SaveGroupAuthRequest from './group/auth/SaveGroupAuthRequest.js';
import SaveGroupAuthResponse from './group/auth/SaveGroupAuthResponse.js';
import SaveChannelAuthRequest from './group/auth/SaveChannelAuthRequest.js';
import SaveChannelAuthResponse from './group/auth/SaveChannelAuthResponse.js';
import AddMemberToGroupAuthRequest from './group/auth/AddMemberToGroupAuthRequest.js';
import AddMemberToGroupAuthResponse from './group/auth/AddMemberToGroupAuthResponse.js';
import RemoveMemberFromGroupAuthRequest from './group/auth/RemoveMemberFromGroupAuthRequest.js';
import RemoveMemberFromGroupAuthResponse from './group/auth/RemoveMemberFromGroupAuthResponse.js';
import DeleteGroupRequest from './group/auth/DeleteGroupRequest.js';
import ChangeGroupAdminRequest from './group/auth/ChangeGroupAdminRequest.js';
import ChangeGroupAdminResponse from './group/auth/ChangeGroupAdminResponse.js';
import DeleteGroupNotice from './group/DeleteGroupNotice.js';
import GroupUpdateNotice from './group/GroupUpdateNotice.js';
import MemberGroupAuthIdUpdateNotice from './group/MemberGroupAuthIdUpdateNotice.js';
import KickMemberNotice from './group/KickMemberNotice.js';
import DeleteGroupMessageNotice from './group/DeleteGroupMessageNotice.js';
import EditGroupMessageNotice from './group/EditGroupMessageNotice.js';
import GroupChatMessageNotice from './group/GroupChatMessageNotice.js';


const protocols = new Map();

const ProtocolManager = {};

ProtocolManager.getProtocol = function getProtocol(protocolId) {
    const protocol = protocols.get(protocolId);
    if (protocol === null) {
        throw new Error('[protocolId:' + protocolId + ']协议不存在');
    }
    return protocol;
};

ProtocolManager.write = function write(buffer, packet) {
    const protocolId = packet.protocolId();
    buffer.writeShort(protocolId);
    const protocol = ProtocolManager.getProtocol(protocolId);
    protocol.write(buffer, packet);
};

ProtocolManager.read = function read(buffer) {
    const protocolId = buffer.readShort();
    const protocol = ProtocolManager.getProtocol(protocolId);
    const packet = protocol.read(buffer);
    return packet;
};

ProtocolManager.initProtocol = function initProtocol() {
    protocols.set(100, Message);
    protocols.set(101, Error);
    protocols.set(102, Heartbeat);
    protocols.set(103, Ping);
    protocols.set(104, Pong);
    protocols.set(111, PairLong);
    protocols.set(112, PairString);
    protocols.set(113, PairLS);
    protocols.set(114, TripleLong);
    protocols.set(115, TripleString);
    protocols.set(116, TripleLSS);
    protocols.set(120, ChatMessage);
    protocols.set(130, TimeKeyHeaderVO);
    protocols.set(131, TimeKeyRowVO);
    protocols.set(132, TimeKeyVO);
    protocols.set(133, TimeLinkAlbumVO);
    protocols.set(134, VideoLinkVO);
    protocols.set(1000, WebsocketSignInRequest);
    protocols.set(1001, WebsocketSignInResponse);
    protocols.set(1002, WebsocketSignOutRequest);
    protocols.set(1003, WebsocketSignOutResponse);
    protocols.set(1300, CreateGroupRequest);
    protocols.set(1301, CreateGroupResponse);
    protocols.set(1310, RefreshChannelTimeRequest);
    protocols.set(1311, RefreshChannelTimeResponse);
    protocols.set(1312, MuteGroupRequest);
    protocols.set(1313, MuteGroupResponse);
    protocols.set(1314, MuteChannelRequest);
    protocols.set(1315, MuteChannelResponse);
    protocols.set(3000, UserCache);
    protocols.set(3021, GetUserCacheRequest);
    protocols.set(3022, GetUserCacheResponse);
    protocols.set(3030, SearchUserRequest);
    protocols.set(3031, SearchUserResponse);
    protocols.set(15000, ApplyFriendVO);
    protocols.set(15001, FriendInfoVO);
    protocols.set(15100, ApplyFriendRequest);
    protocols.set(15102, RejectFriendRequest);
    protocols.set(15103, RejectFriendResponse);
    protocols.set(15104, AcceptFriendRequest);
    protocols.set(15106, DeleteFriendRequest);
    protocols.set(15107, DeleteFriendResponse);
    protocols.set(15108, BlacklistRequest);
    protocols.set(15109, BlacklistResponse);
    protocols.set(15110, BlacklistCancelRequest);
    protocols.set(15111, BlacklistCancelResponse);
    protocols.set(15112, MarkFriendRequest);
    protocols.set(15113, MarkFriendResponse);
    protocols.set(15200, FriendChatRequest);
    protocols.set(15202, ReadFriendMessageRequest);
    protocols.set(15203, ReadFriendMessageResponse);
    protocols.set(15204, FriendHistoryMessageRequest);
    protocols.set(15205, FriendHistoryMessageResponse);
    protocols.set(15206, DeleteFriendMessageRequest);
    protocols.set(15208, EditFriendMessageRequest);
    protocols.set(16000, FriendMessageNotice);
    protocols.set(16001, NewApplyFriendNotice);
    protocols.set(16002, NewFriendNotice);
    protocols.set(16003, DeleteFriendMessageNotice);
    protocols.set(16004, EditFriendMessageNotice);
    protocols.set(18000, GroupVO);
    protocols.set(18001, GroupAuthVO);
    protocols.set(18010, ChannelVO);
    protocols.set(18011, ChannelBoxVO);
    protocols.set(18012, ChannelAuthVO);
    protocols.set(18013, GroupMemberSimpleVO);
    protocols.set(18014, GroupTimeVO);
    protocols.set(18015, ChannelTimeVO);
    protocols.set(18100, GroupChatRequest);
    protocols.set(18102, GroupHistoryMessageRequest);
    protocols.set(18103, GroupHistoryMessageResponse);
    protocols.set(18105, DeleteGroupMessageRequest);
    protocols.set(18107, EditGroupMessageRequest);
    protocols.set(18109, PinGroupMessageRequest);
    protocols.set(18110, DeleteGroupPinMessageRequest);
    protocols.set(18111, DeleteGroupPinMessageResponse);
    protocols.set(18112, GroupHistoryPinMessageRequest);
    protocols.set(18113, GroupHistoryPinMessageResponse);
    protocols.set(18200, SaveGroupAvatarRequest);
    protocols.set(18201, SaveGroupAvatarResponse);
    protocols.set(18202, SaveGroupBackgroundRequest);
    protocols.set(18203, SaveGroupBackgroundResponse);
    protocols.set(18204, SaveGroupSettingRequest);
    protocols.set(18205, SaveGroupSettingResponse);
    protocols.set(18206, RefreshGroupNameRequest);
    protocols.set(18300, CreateChannelBoxRequest);
    protocols.set(18301, CreateChannelBoxResponse);
    protocols.set(18302, CreateChannelRequest);
    protocols.set(18303, CreateChannelResponse);
    protocols.set(18304, DeleteChannelBoxRequest);
    protocols.set(18305, DeleteChannelBoxResponse);
    protocols.set(18306, DeleteChannelRequest);
    protocols.set(18307, DeleteChannelResponse);
    protocols.set(18308, SaveChannelRequest);
    protocols.set(18309, SaveChannelResponse);
    protocols.set(18310, SaveChannelBoxRequest);
    protocols.set(18311, SaveChannelBoxResponse);
    protocols.set(18400, InviteCodeVO);
    protocols.set(18401, GroupMemberVO);
    protocols.set(18410, CreateInviteGroupCodeRequest);
    protocols.set(18411, CreateInviteGroupCodeResponse);
    protocols.set(18412, JoinGroupRequest);
    protocols.set(18413, JoinGroupResponse);
    protocols.set(18414, JoinGroupByUserIdRequest);
    protocols.set(18420, DeleteInviteGroupCodeRequest);
    protocols.set(18421, DeleteInviteGroupCodeResponse);
    protocols.set(18422, LeaveGroupRequest);
    protocols.set(18423, LeaveGroupResponse);
    protocols.set(18424, AllInviteGroupCodeRequest);
    protocols.set(18425, AllInviteGroupCodeResponse);
    protocols.set(18430, GroupMemberListRequest);
    protocols.set(18431, GroupMemberListResponse);
    protocols.set(18432, GroupMemberInfoRequest);
    protocols.set(18433, GroupMemberInfoResponse);
    protocols.set(18434, KickMemberRequest);
    protocols.set(18435, KickMemberResponse);
    protocols.set(18500, CreateGroupAuthRequest);
    protocols.set(18501, DeleteGroupAuthRequest);
    protocols.set(18502, SaveGroupAuthRequest);
    protocols.set(18503, SaveGroupAuthResponse);
    protocols.set(18512, SaveChannelAuthRequest);
    protocols.set(18513, SaveChannelAuthResponse);
    protocols.set(18520, AddMemberToGroupAuthRequest);
    protocols.set(18521, AddMemberToGroupAuthResponse);
    protocols.set(18522, RemoveMemberFromGroupAuthRequest);
    protocols.set(18523, RemoveMemberFromGroupAuthResponse);
    protocols.set(18530, DeleteGroupRequest);
    protocols.set(18535, ChangeGroupAdminRequest);
    protocols.set(18536, ChangeGroupAdminResponse);
    protocols.set(19000, DeleteGroupNotice);
    protocols.set(19001, GroupUpdateNotice);
    protocols.set(19002, MemberGroupAuthIdUpdateNotice);
    protocols.set(19003, KickMemberNotice);
    protocols.set(19004, DeleteGroupMessageNotice);
    protocols.set(19005, EditGroupMessageNotice);
    protocols.set(19006, GroupChatMessageNotice);
};

export default ProtocolManager;
